grpc.client.chat.negotiation-type: plaintext
spring:
  main:
    web-application-type: none
  kafka:
    streams:
      application-id: chatgpt-filter

jwt.secret: localsecretlocalsecretlocalsecre # TODO remove (conditional beans)

chatgpt: # should match chatgpt values in users table
  mention: "@GoshağŸ¤–"
  user-id: -1
  loading-message: "â³"
  error-message: "ğŸ¤·â€â™‚ï¸"

openai.model: gpt-4o-mini